#!/bin/bash

mol=octane
gro=trial-${mol}.gro
trial=attrial-${mol}

printf "%4s %4s %4s %4s %4s\n" wnr wal wbb wab num
for wnr in 50 55 60 65; do
  for wal in 0.12 0.16 0.18 0.20; do
    for wbb in 1.6 1.8 2.0 2.2; do
      for wab in 0.7 0.8 0.9 1.0; do
        cp auto-martini-template $trial
        sed -i "s/WNR/$wnr/g" $trial
        sed -i "s/WAL/$wal/g" $trial
        sed -i "s/WBB/$wbb/g" $trial
        sed -i "s/WAB/$wab/g" $trial
        ./$trial --mol MOL \
          --smi "CCCCCCCC" --gro $gro > /dev/null
        num=$(head -n 2 $gro| tail -1 | awk '{print $1}')
        printf "%4.1f %4.2f %4.2f %4.2f %4d\n" $wnr $wal $wbb $wab $num
        rm $gro
      done
    done
  done
done
