#!/bin/bash

mol=dodecane
gro=trial-${mol}.gro
trial=attrial-${mol}

printf "%4s %4s %4s %4s %4s\n" wnr wal wbb wab num
for wnr in 48 50 52; do
  for wal in 0.17 0.18 0.19; do
    for wbb in 1.9 2.1 2.3; do
      for wab in 0.75 0.80 0.85; do
        cp auto-martini-template $trial
        sed -i "s/WNR/$wnr/g" $trial
        sed -i "s/WAL/$wal/g" $trial
        sed -i "s/WBB/$wbb/g" $trial
        sed -i "s/WAB/$wab/g" $trial
        ./$trial --mol MOL \
          --smi "CCCCCCCCCCCC" --gro $gro > /dev/null
        num=$(head -n 2 $gro| tail -1 | awk '{print $1}')
        printf "%4.1f %4.2f %4.2f %4.2f %4d\n" $wnr $wal $wbb $wab $num
        rm $gro
      done
    done
  done
done
