#!/bin/bash

mol=dodecane
gro=trial-${mol}.gro
trial=attrial-${mol}

printf "%4s %4s %4s %4s %4s\n" wnr wal wbb wab num
for wnr in 50; do
  for wal in 0.20; do
    for wbb in 5.0 7.5 10.0 12.5 15.0; do
      for wab in 0.90; do
        cp auto-martini-template $trial
        sed -i "s/WNR/$wnr/g" $trial
        sed -i "s/WAL/$wal/g" $trial
        sed -i "s/WBB/$wbb/g" $trial
        sed -i "s/WAB/$wab/g" $trial
        ./$trial --mol MOL \
          --smi "CCCCCCCCCCCC" --gro $gro > /dev/null
        num=$(head -n 2 $gro| tail -1 | awk '{print $1}')
        printf "%4.1f %4.2f %4.1f %4.2f %4d\n" $wnr $wal $wbb $wab $num
        rm $gro
      done
    done
  done
done
